### ISSUE TITLE
Error: unable to open url: <urlopen error no host given>

### ISSUE THREAD

**Issue by schniggie** [segment-srl/htcap#7]
I'm trying to use htcap with BurpSuite. However that always fails. Any hints?

```
root@kali:~/offsec/htcap# python htcap.py crawl -p http://localhost:8080 heise.de test.db
Initializing . 
Error: unable to open url: <urlopen error no host given>
root@kali:~/offsec/htcap# 
```

Without the -p flag it works.

**Comment by segment-srl** [comment]
Hi,
the correct syntax for -p option is: "protocol:host:port", in your case "http:localhost:8080"

**Comment by schniggie** [comment]
Thanks :) My fault ...
