### ISSUE TITLE
Is htcap.org owned by this project?

### ISSUE THREAD

**Issue by cakoose** [segment-srl/htcap#89]
This project's readme links to htcap.org, but when I go there, I get redirected to some sketchy Chrome extension:

<img width="1396" alt="Screen Shot 2021-09-28 at 22 04 53" src="https://user-images.githubusercontent.com/239989/135206594-1fee9585-520c-4721-bd2c-94228a0b6b9a.png">

Is something wrong?

**Comment by fcavallarin** [comment]
Yes we definitely had a problem.. htcap.org is gone .. I updated the README accordingly
